### ISSUE TITLE
login方法已经失效了

### ISSUE THREAD

**Issue by NKUlpj** [JiayangWu/LeetCodeCN-Submissions-Crawler#10]
我试了很多遍，目前定位到的是大概在第一页page=0爬取完毕后，login的状态变为未登录，导致后续爬取失败！

**Comment by NKUlpj** [comment]
改了几处代码，当获取的client验证失败时重新获取！
1、 主函数中，传入三个参数scraping(client,email,password)
2、scraping函数增加2个参数，while语句中的分支改为 
```
if "submissions_dump" not in html:
            print ("Warning! No previous submission is detected, please make sure you are logging in the correct account AND you once submitted codes on leetcode-cn.com")
            client = login(email, password)
            continue

```
3、while跳出的条件改为
`   while page_num<=1581:`这个值为lc的总题目数，可以在网站上找到！


运行过程中一直会有warning输出，猜测应该是lc登录接口做了限流，文件中是5ms发送一次，可以调大点

**Comment by JiayangWu** [comment]
你好，最近还有这种问题吗？
我今天测试了一下，没有发现你描述的问题1：page=0之后变成未登录。2：不停弹warning。
以下是我的日志：

> login
Login successfully!
start scrapping
Now for page: 0
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/面试题03.数组中重复的数字/面试题03-数组中重复的数字.py
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/面试题65.不用加减乘除做加法/面试题65-不用加减乘除做加法.py
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/面试题66.构建乘积数组/面试题66-构建乘积数组.py
把字符串转换成整数 was not Accepted, continue for the next submission
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/面试题68-I.二叉搜索树的最近公共祖先/面试题68-I-二叉搜索树的最近公共祖先.py
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/面试题68-II.二叉树的最近公共祖先/面试题68-II-二叉树的最近公共祖先.py
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/0050.Pow(x,n)/0050-Pow(x,n).py
和为K的最少斐波那契数字数目 failed! Due to unknown Pid! 
和为K的最少斐波那契数字数目 failed! Due to unknown Pid! 
逐步求和得到正数的最小值 failed! Due to unknown Pid! 
HTML实体解析器 failed! Due to unknown Pid! 
HTML实体解析器 was not Accepted, continue for the next submission
查询带键的排列 failed! Due to unknown Pid! 
数组中的字符串匹配 failed! Due to unknown Pid! 
数组中的字符串匹配 failed! Due to unknown Pid! 
数组中的字符串匹配 failed! Due to unknown Pid! 
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/0069.x的平方根/0069-x的平方根.py
Now for page: 20
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/0221.最大正方形/0221-最大正方形.py
重新格式化字符串 failed! Due to unknown Pid! 
重新格式化字符串 failed! Due to unknown Pid! 
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/0572.另一个树的子树/0572-另一个树的子树.py
另一个树的子树 was not Accepted, continue for the next submission
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/0098.验证二叉搜索树/0098-验证二叉搜索树.py
验证二叉搜索树 was not Accepted, continue for the next submission
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/0053.最大子序和/0053-最大子序和.py
Writing ends! /Users/wujiayang/Documents/GitHub/LeetCode-Python/0021.合并两个有序链表/0021-合并两个有序链表.py
end scrapping
~~~~~~~~~~~~~git add . finished! ~~~~~~~~

**Comment by JiayangWu** [comment]
超过14天没有得到回复，关闭此issue。
